### ISSUE TITLE
[Refactor] Might example is broken

### ISSUE THREAD

**Issue by alphastrata** [alphastrata/shadplay#101]
**what are we refactoring?**
The Might Example

**why?**
Because it's not been updated for 0.15.0 glory!

**Comment by mpowell90** [comment]
Just fired up shadplay and the Might example, and fixed it to test it out. Are happy for me to open a PR with the fix?

**Comment by alphastrata** [comment]
> Just fired up shadplay and the Might example, and fixed it to test it out. Are happy for me to open a PR with the fix?

Always happy for contributions!

**Comment by mpowell90** [comment]
@alphastrata PR is up: https://github.com/alphastrata/shadplay/pull/103
