### ISSUE TITLE
Mac OSX window misbehaving

### ISSUE THREAD

**Issue by RJ** [alphastrata/shadplay#27]
`cargo run --release` on Mac M1 running OS X 13.2.1 (22D68)

window appears on top but can't be moved and doesnt respond to anything.

had to revert to `decorations: true` and removing `window_level: WindowLevel::AlwaysOnTop` to make it play nice.

**Comment by alphastrata** [comment]
aiit so decorations are supported on mac && windows, but because you need to have accessibility/window-manager type features etc on that are a separate install I've just configured them to not be on by default on those OS'
