### ISSUE TITLE
how to run example shaders?

### ISSUE THREAD

**Issue by johnny-smitherson** [alphastrata/shadplay#52]
Is there a list with example/gallery shaders that one can go through, inside the program, or must they be copy/pasted into the main shader file one at a time?

**Comment by alphastrata** [comment]
> Is there a list with example/gallery shaders that one can go through, inside the program, or must they be copy/pasted into the main shader file one at a time? 

You can  drag and drop the example ones directly onto the window ( if they're valid), or you can just save things as the myshader_2d.wgsl (not 2m obviously when you're on a 3D shape)
