### ISSUE TITLE
[BUG] No file-drop on wayland

### ISSUE THREAD

**Issue by alphastrata** [alphastrata/shadplay#64]
**What happened**
Drag n drop for textures and shaders is not working properly on wayland (hyprland wm).

** RUSTC **
```rustc 1.75.0-nightly (a2f5f9691 2023-11-02)
binary: rustc
commit-hash: a2f5f9691b6ce64c1703feaf9363710dfd7a56cf
commit-date: 2023-11-02
host: x86_64-unknown-linux-gnu
release: 1.75.0-nightly
LLVM version: 17.0.4```

**ERROR**
N/A

**Comment by alphastrata** [comment]
closing this is it's a xdg-desktop thing -- which is too specific to my exact setup.

**Comment by Soupborsh** [comment]
Hello, I am using KDE Plasma on Arch Linux and it does not work for me on wayland too, however, works it on xorg.

**Comment by alphastrata** [comment]
@Soupborsh  yeah it's not supported well on Wayland, `winit`'s problem not ours
