### ISSUE TITLE
[BUG] 3D Shape gets duplicated when toggling between 2D and 3D

### ISSUE THREAD

**Issue by DTibbs** [alphastrata/shadplay#65]
**What happened**
I saw multiple 3d shapes when switching between 2d and 3d mode

** RUSTC **
`rustc -Vv` 
rustc 1.72.0 (5680fa18f 2023-08-23)
binary: rustc
commit-hash: 5680fa18feaa87f3ff04063800aec256c3d4b4be
commit-date: 2023-08-23
host: x86_64-pc-windows-msvc
release: 1.72.0
LLVM version: 16.0.5

**ERROR** (Not really related, more of a side effect?)
```shell
 ERROR shadplay::shader_utils::texture_tooling: No handle, it could still be loading your texture into the ECS!
```

Steps to reproduce:

1. Start shadplay with `cargo run --release`
2. Toggle 3D mode with `h`
3. Change 3D shape to something that would make it obvious multiple shapes have been created, I did cube and torus as test.
4. Toggle 3D rotation with `r`
5. Toggle back to 2D mode with `t`
6. Quickly toggle back go 3D mode with `h`
7. Repeat 5&6 a few times, notice multiple 3D shapes were created.

CL `cadfdb7`

**Comment by alphastrata** [comment]
![image](https://github.com/alphastrata/shadplay/assets/25101888/f03d0d99-1802-4941-abc6-b433137f7334)
verified!
