### ISSUE TITLE
[FEAT] A help-/status-overlay that displays all relevant shortcuts. 

### ISSUE THREAD

**Issue by exo-cortex** [alphastrata/shadplay#74]
When pressing F1 there could appear a (maybe slightly transparent) overlay that displays all relevant shortcuts - the ones that are in the `README.md`. F1 could either toggle the commands, or only show them while pressed.

Other information that could appear in this overlay could be:
-framerate
-information about the graphics card
-shadplay version number

**Comment by exo-cortex** [comment]
Thank you.
Maybe this could be mentioned in the Readme atop of the shortcut-table.

**Comment by alphastrata** [comment]
> Thank you.
> 
> Maybe this could be mentioned in the Readme atop of the shortcut-table.
> 
> This tool is really fun!
> 
> 
> 
> One thing that could be nice: a path in the config.toml that stores a user's shaders. The program could also be started with a path given to the user's shader-folder.
> 
> (btw is it ok if I dump any ideas that I have into this thread?)
> 
> 

Go for it!

Why keep shaders somewhere other than the assets/shaders path? Just out of curiosity -- it's where bevy looks for them by default, or are you thinking it as some way of extending the versioning system (which I'm totally into btw)
